# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  quanlysinhvien:
    image: quanlysinhvien
    build:
      context: .
      dockerfile: quanlysinhvien/Dockerfile
    ports:
      - 5212:5212
